apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: cap-processamento
  namespace: cap-service
  labels:
    app: cap-processamento
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: cap-processamento
  service:
    name: cap-processamento
    port: 80
  rules:
    - path: /.*
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      accessStrategies:
        - handler: noop
      mutators: []
