
---
apiVersion: v1
kind: Config
current-context: kyma-lab-k1lbfebj-3kccux8b
clusters:
- name: kyma-lab-k1lbfebj-3kccux8b
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRUTMwWmpwajcxZ0taVzhaWFVJWTdJakFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TmpBME1EWXhOelEwTlRkYUZ3MHpOakEwTURZeE56UTFOVGRhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUEwZVlRClBVWDFCeHErSjhPczZiQjZORlBKejZZS0E0TldsMFFEV3dtcXY3a0E0S3VpMDBGWllxQ1pOeVZlZTluZHFRS1IKWXVncDBoek94c3VzU3M2M0hVOS9QajNoVkJFTkJFcHZzS0Q3OXJOY3UxK2xhT1dLSVAxeUdsRjg4YVVLcGdnQQpnczUwQTJ5bW1ySHlJMHBOVnFZL2EvQ0M5VzEvM0ZkL2ZaNyttNFU5ZEJqT0JzQzM2R3R5QXovakQxZFgvSjFWCjB0cDRqOXVzOXUwQkpxZXN3ZUE4Vlh5YzhmWUxha24yZlRaTnhIRllxY3JBVnNTZHdxZUdmRWg3R0JuV1VONVoKU0R6c2poZEk2USttbmRNR25xY1FIUkMxUFBuQ2VidjZNVThaNS93WElPS09IcnpiOGlSa09KcnFnVjVNdG9kKwo0MHF1M3Q1Q3JQV3FkL2N5WUVmL24wTGdJSmt3R3hCc3ROdGRaRHViSUNzZ21aWFdKWkVvTVZNU00xV0U5UzQ3CjBxTDM4TmtyKzEvVlhBbGp1OVlzUEUwZTMwelV0N21WRFRUN3F4dklORWZnZzZhU3ZXandndFVwdzZVSXF4eUEKQ1YyenkrNlNjaEp3WlJmMytJbmJKdkxqdytyT3FaTGFRdjVsSWNESHNtcWlSQVlxRk14S3JpWlYwY1FWQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCVGhXaU1lZ29VTFFCUHFYRkxxVkpBT0JrWVA5VEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBY1crWWs0VTcKY0JJeGVTbVBZOEJvUFk5ZkZuR2taSmlDQXVvenI3eEl2S0I3QTVDZ0NaZjFxMW1zdEdUZ3p1eS9BZ2hidllubQpzcmZlY1Rpbk5LMk80Y2NyMW96SkVsSmhXK0g5S094ejZTaVlZbU1CRTdWbGZ2VWk3M1BWeGgvbWRHQThUVVc3CmlPMTVJUXlpL1l5dUZhdy9Lb2lhcWVzdlUrc1ZraHJjd2NBTjlCbmZiRGV2WjF6a2NjU0FhRmEwNHREZmwreTUKTG42RitibWNKZWdsS1FiTUNLaVFzdnMxeUZXWldmSUkyNVZPZXVtVk9VQ3k0dmtOc1hNclJtUkxEV2NWZ2ZXNwpJNVRlemRrNWRXY0k5Z3BvZ2xxS0Nkd2hyaEY1QXZHVG5qc2ZpMlBWOUlKYVZlcEs3K0JSS2oySGo2blBVY2lOCnlkaWtBZHYrUWdaczdrNnVHeng0L2liNVBlTVZ4TUVMTFNIdWRVM0tLckpJbFROWGVMUWE5Q2Vrc1BmTUNLWFUKWVZxYVovNXJzUGhDR2xoQURsOHhwTDI5ajFtbnlGMVQrbHA1M2F3V1lDWGU0SU5oV1kyemdGb3ZKbVZ5cWo3aAppVnhNMkQxV25QMWh2OGFBMHBLNmVyS2VyalV4a2F6OVdOVSswMytqWGQ3RDdMM3lsRkFGSUVZZwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.daa4683.kyma.ondemand.com
contexts:
- name: kyma-lab-k1lbfebj-3kccux8b
  context:
    cluster: kyma-lab-k1lbfebj-3kccux8b
    user: kyma-lab-k1lbfebj-3kccux8b
users:
- name: kyma-lab-k1lbfebj-3kccux8b
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
